name: Build and Push Caddy+Coraza

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest Caddy version
        id: caddy
        run: |
          latest=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r .tag_name)
          echo "version=${latest#v}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            --build-arg CADDY_VERSION=${{ steps.caddy.outputs.version }} \
            -f Containerfile \
            -t ghcr.io/${{ github.repository_owner }}/caddy-coraza:${{ steps.caddy.outputs.version }} .

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/caddy-coraza:${{ steps.caddy.outputs.version }}
          docker tag ghcr.io/${{ github.repository_owner }}/caddy-coraza:${{ steps.caddy.outputs.version }} ghcr.io/${{ github.repository_owner }}/caddy-coraza:latest
          docker push ghcr.io/${{ github.repository_owner }}/caddy-coraza:latest
